### ISSUE TITLE
installation of module eq_purchase raises error

### ISSUE THREAD

**Issue by baeumer** [equitania/myodoo-addons-v10#2]
I tried to install the modules _eq_purchase_ and _eq_account_. Both brings up the following error and installation was not completed. Other modules like _eq_sale_, _eq_base_ and other were installed successfully before.

```  File "/opt/odoo/odoo-server/odoo/osv/expression.py", line 821, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ParseError: "Invalid field 'eq_email_template_version' in leaf "<osv.ExtendedLeaf: ('eq_email_template_version', '=', False) on mail_template (ctx: )>"" while parsing /opt/odoo/odoo-server/addons/eq_purchase/data/email_template_function.xml:5, near
<function model="eq_install_func" name="_eq_delete_default_templates" eval="[('eq_purchase')]"/>
```

Is there a special order in which the Equitania modules should be installed?

**Comment by fiee** [comment]
These modules depend on eq_mail_extension. The dependency is undocumented, otherwise it would have been installed automatically.

**Comment by baeumer** [comment]
That was the solution. It worked out. Thanks for your help.
